name: Daddys Boys
favicon: null
layout_spectrum: 0.31495
typography_spectrum: 0.27487
title: Daddys Boys
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2934056918602437
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 0.178835557308048
purpose: []
