name: Daddys Boys - Fucked by the cameraman
favicon: null
layout_spectrum: 0.5029
typography_spectrum: 0.27487
title: 'Daddys Boys - POV style - models get fucked by the director - Coming Soon!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-1421578-9
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2934056918602437
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.178835557308048
purpose: []
